language: bash
services: docker
before_install:
  - echo "we are in the docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "&{DOCKER_PASSWORD}" | docker login --username "&{DOCKER_USERNAME}" --password-stdin
deploy:
  provider:script
  script:
    docker push edilsonbsfilho/mysql-rest-with-spring-boot-udemy;
    docker push edilsonbsfilho/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false