version: '3.4'
services:
  db:
    image: edilsonbsfilho/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: db_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-spring-boot-udemy:
    image: edilsonbsfilho/rest-with-spring-boot-udemy
    restart: always
    build: ./RestWithSpringBootUdemy
    working_dir: /project
    environment:
      TZ: America/Sao_Paulo
      SPRING-BOOT-ENVIRONMENT: Production
    volumes:
      - ./RestWithSpringBootUdemy:/project
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
  Jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home:rw
networks:
    udemy-network:
        driver: bridge
volumes:
  jenkins_data:
    name: jenkins_data